### ISSUE TITLE
Google 2FA Enable and Disable working perfectly but One time Password not working in laravel 5.5. which url for one time password, please help me.

### ISSUE THREAD

**Issue by rinkesh-prajapat** [antonioribeiro/google2fa#94] opened 2018-03-01 09:56 UTC
I have use package
composer require pragmarx/google2fa-laravel
composer require bacon/bacon-qr-code
and my reference url is - https://www.5balloons.info/two-factor-authentication-google2fa-laravel-5/

**Comment by antonioribeiro** [comment] 2018-03-07 17:58
This is a duplicate of the other issue.

**Closed by antonioribeiro** 2018-03-07 17:58 UTC
