### ISSUE TITLE
broken img link on google2fa qrcode

### ISSUE THREAD

**Issue by galiavni** [antonioribeiro/google2fa#201] opened 2024-04-28 09:47 UTC
Hi 
I am using goole2fa package by pragrmix on my application.
lately, I  get a broken link for my  qr-code image.
I did not touch my code.
The appliction is Php- back end  and Angular-front  end.

This is the generated link :
https://chart.googleapis.com/chart?cht=qr&chs=300x300&chl=otpauth://totp/My-cliniq:avni.gali%40gmail.com76?secret=ERP4QMMZ7CLLA6AF&issuer=My-cliniq&algorithm=SHA1&digits=6&period=30

Thank you.

**Comment by mfn** [comment] 2024-04-28 13:36
Duplicate of https://github.com/antonioribeiro/google2fa/issues/199

**Closed as completed** 2024-10-13 20:18 UTC
